; ============================================================
;  GeoTrack-Agro — NODO TRANSMISOR
;  Hardware : ESP32 + RFM69HCW + GPS NEO-6M + DHT22
; ============================================================
[env:esp32]
platform  = espressif32
board     = esp32dev
framework = arduino

lib_deps =
    ; LoRa RFM69
    LowPowerLab/RFM69 @ ^1.5.1
    ; GPS
    mikalhart/TinyGPSPlus @ ^1.0.3
    ; DHT sensor
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14

monitor_speed = 115200
build_flags   = -DCORE_DEBUG_LEVEL=0